version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php73
    depends_on:
      - db
    image: php:8.0-apache
    environment:
      DB_HOST: db
      DB_NAME: php_exam
      DB_USER: app
      DB_PASS: password
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8080:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password_root
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: php_exam
    volumes:
      - ./db:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: app
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 20M
    ports:
    - 8899:80
